
server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456


mybatis:
  type-aliases-package: com.echo.spring_mybatis.pojo
  mapper-locations: classpath:/mapper/*.xml


logging:
  file:
    name: log/log.log
  level:
    root: info
    spring_mybatis: debug
